### ISSUE TITLE
请问如何参入到xsadmin的开发,需要哪些知识?

### ISSUE THREAD

**Issue by n7then** [alishtory/xsadmin#8]
Hi,大佬..

萌新想问下开发这个项目包括后端需要哪些知识,可以针对的去学习.. 或许有幸还可以一起开发.

**Comment by Ehco1996** [comment]
我也是初学者 ，
其实这个主要是前端知识了，你得会css js 
后端的话学一点django linux之类的
另外我也写了一个panel 练手：https://github.com/Ehco1996/django-sspanel
有兴趣可以看看，

**Comment by n7then** [comment]
Got. 有个路线不至于懵逼,多谢.!
